apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard 
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-source 
spec:
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard 
